spring:
  application:
    name: encryption-service


encryption:
  public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz98hcTIQJa5VTK7KENJB430IxcWpEu6/VcFqApFdGpGR19rd/CacB6232cK/O6bmHUGDsJzEZ0cjynlU7xoy/7weSf9pebh24GJ8P8xEXwLkgxSgTHIjntgBaUWDT3Q+SvMJ2AklNZ0GhsctroNRmGPQU6zpfGflZWh0MPOCjhegyHTUh7JslwvzZz1Z3wZ3q3WGLHkpm5fIPMqjDDkiu7kLV3yhhfCw45BGMScPjR6ugWGrVKlhXYZjNpVT1TXiwVaVN0I4XtgV78x79kAlqTXJYicu61uGeN82gFwdWAjTsJbfnTpI/U1mmJC1kuPZeTc7fOzuXGouIN8cdO09LwIDAQAB"
  private-key: "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDP3yFxMhAlrlVMrsoQ0kHjfQjFxakS7r9VwWoCkV0akZHX2t38JpwHrbfZwr87puYdQYOwnMRnRyPKeVTvGjL/vB5J/2l5uHbgYnw/zERfAuSDFKBMciOe2AFpRYNPdD5K8wnYCSU1nQaGxy2ug1GYY9BTrOl8Z+VlaHQw84KOF6DIdNSHsmyXC/NnPVnfBnerdYYseSmbl8g8yqMMOSK7uQtXfKGF8LDjkEYxJw+NHq6BYatUqWFdhmM2lVPVNeLBVpU3Qjhe2BXvzHv2QCWpNcliJy7rW4Z43zaAXB1YCNOwlt+dOkj9TWaYkLWS49l5Nzt87O5cai4g3xx07T0vAgMBAAECggEAX/HENMP/sfSySE+Q0ozJfp+Scf5WmHd79q/sJz1C9OVlpHTP6vdDI0QqTKdXrsfNBIndp6HkAStTuLuh2S6FhYYlkNADtfvPWqf6Y1P75sKmCF530nEIQeO/WwCLqBumON/Ollk6RHGytniufBL+kVDYshZoOlSWC+VXY9SxWLV4PEotfqPditscaXmFY1UX4O1ezssS6TrphP3f9Ku74NiI0Gi87K3QghcGuigrMYQEgDhHXEhKK4Ps37nKjJhvlu5DsgKXTn4l2LUJ4OKh1Ub+lgknyjAOVw3qF/x0HAfs3Er9+pXUqsmU3njXowfs2T2wDdcDijK+XL2cbZoWEQKBgQDmVfkxJyEy2vPbAhVNNIaTJhdZgWMkhgLu0CiMozpLVz9mR9uuHkvuCFswFnjR3WMqb7dAyQTehrA1iFNRoQSzDiXrjTGDaYSF9pR9+7RE7zwPR3P+ChqRQ7PKKBk7otOdzglnb1Djr5n/eMBBfqeEMwufW89SCHzATXVxC/+LBwKBgQDnCGUG0e+P4gUpPX2R9f6mqgCiWsoKbi7asdL0MHKeyVOJ0Z+aM0sK2BjN4xq58beoFf4AT+EWB+nNEasKrBJpuETo3UXi4Nmw55UmGlRWQzs5Vo/EE1TGIGhShlRmQtiIOHRH71H/U5bIl92aqdDnVlA6J/qJUWUEJKRIk3wqmQKBgHyhhl1vQ8plqM8XGHmW8z5JvRakKQYJMSsRHO/EHnXHtrlcJmTXZdRdVyH09tjvhoneuvRmEKlrjYrZweOIUaek/yWuV104yglGe+CTQl6OaBwIWJ3bz7ZMQMsg2U5oc0KOyo3aMJWSXaxbJQQLSQ8CI8bNgadsijvvbZ2GlXYfAoGAYYWZn5demE2///iE2OgN5iw8uEu6nUyFWqtVcN5Cg+RX7wUdaenc82bkkYQb9AGklL8zyM3vJW2Rs46RtJ+N5jJyZBmDNpHTUmlu+/aBQyh+B2YSqaG/VyK25p7tYX02CcpKy1KqOiz+qQ3x7Sdhl0VH+ESH7Q7+pRESh9A5yYECgYB6UccElwghUEPY0qTjFE55PuRVZ6vDOrFwR6oJqLpr8kGS0jjSJowjs72AXYkamxV4a84q3rgnAo7lstgB0uhLAWYjxMOspk4uD7xz6DLrC36lu+nC/pGdeKmJxWDJdBZJZN/Dlx2sz+77Me4OtHa3vE9GZGECDN/jc1xn+BQefQ=="
  aes-key: "1DIqv/29z46jVKZa9erLRLLKdveqpt1chFwHm5Za1eA="
  iv: "4t/bawbbav5hV+ligfdI0Q=="

springdoc:
  api-docs:
    path: /swagger-doc/v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-doc/swagger-ui.html

info:
  project:
    version: "@project.version@"
    title: "@project.name@"
    description: "@project.description@"